### PR TITLE
Get branch by name instead of id

### PR DESCRIPTION
**Pull request by ivanfoo**
All test passed, just failing in Travis

### CODE REVIEW

**Comment by tcr-ableton** [comment]
Thanks for this pull request @ivanfoo (and sorry for the late reply)

First of all, I will repost here the pull request purpose explanation you sent me by email. That way its purpose shall be more explicit.

```
I started to use https://github.com/Ableton/go-travis and I opened a PR.
I changed one of the methods of the branches service, because I think looking for a branch by his name it's more useful than by his id.
```

I tend to agree with you, intuitively users want to fetch branches on a per-name basis. However, the TravisCI exposing both options we decided to go for the ID selection as it felt in our opinion closer to REST design principles.

Also, the `Repositories` service exposes both options:
- `func (rs *RepositoriesService) Get(id uint) (*Repository, *http.Response, error)`
- `func (rs *RepositoriesService) GetFromSlug(slug string) (*Repository, *http.Response, error)`

Therefore I'd like to integrate your change following the same pattern: as a second method with the following prototype `func (bs *BranchesService) GetFromSlug(slug string) (*Branch, *http.Response, error)`. This way, the change matches with the global design of the application.

What do you think about this idea? And would you like to integrate the change yourself, or should I take care of it?

Cheers

**Comment by ivanfoo** [comment]
Hi,

Yeap, your suggestion makes all the sense, I'll do the changes : )

Thanks!

On Mon, Jan 4, 2016 at 9:59 AM, Theo Crevon notifications@github.com
wrote:

> Thanks for this pull request @ivanfoo https://github.com/ivanfoo
> 
> First of all, I will repost here the pull request purpose explanation you
> sent me by email. That way its purpose shall be more explicit.
> 
> I started to use https://github.com/Ableton/go-travis and I opened a PR. I changed one of the methods of the branches service, because I think looking for a branch by his name it's more useful than by his id.
> 
> I tend to agree with you, intuitively users want to fetch branches on a
> per-name basis. However, the TravisCI exposing both options we decided to
> go for the ID selection as it felt in our opinion closer to REST design
> principles.
> 
> Also, the Repositories service exposes both options:
> - func (rs _RepositoriesService) Get(id uint) (_Repository,
>   *http.Response, error)
> - func (rs _RepositoriesService) GetFromSlug(slug string)
>   (_Repository, *http.Response, error)
> 
> Therefore I'd like to integrate your change following the same pattern: as
> a second method with the following prototype func (bs _BranchesService)
> GetFromSlug(slug string) (_Branch, *http.Response, error). This way, the
> change matches with the global design of the application.
> 
> What do you think about this idea? And would you like to integrate the
> change yourself, or should I take care of it?
> 
> Cheers
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Ableton/go-travis/pull/5#issuecomment-168615435.

## 

_Iván Sánchez_
DevOps _| *source{d} http://sourced.tech/
GitHub https://github.com/ivanfoo *| Twitter *_| LinkedIn*

_Raimundo Fernández Villaverde 45, 1A_
_28003 Madrid, Spain_

**Comment by tcr-ableton** [comment]
Thanks!

Waiting for changes then :-)

Oh and tests should be green again now.

**Comment by tcr-ableton** [comment]
Hey @ivanfoo any news on this? :rocket:

**Comment by ivanfoo** [comment]
Sorry for the delay @tcr-ableton! I added a new method, instead of changing the existing one (as you suggested)

**Comment by dmitshur** [comment]
Two questions:
1. I think this change looks good, and I'd like to use it. When will it be merged?
2. If I were to use the "get branch via id" functionality, where can I find out what id each branch is?

**Comment by tcr-ableton** [comment]
There we go! 
Thanks for the contribution @ivanfoo !

**Comment by tcr-ableton** [comment]
Hey @shurcooL 
In theory you should be able to find a branch id by listing all the branches of a repository :-)

**Comment by dmitshur** [comment]
> In theory you should be able to find a branch id by listing all the branches of a repository :-)

But how would I know which branch (name) is which id? Listing all branches of a repository seems to only give their ids, so I don't see a way of figuring out which branch is which. Aside from using the lookup-by-name, of course.

**Pull request merged**
